AWSTemplateFormatVersion: 2010-09-09

Description: Converting snapshot to volume and attaching to new instance

Parameters:
  volumename:
     Type: String
     Description: Enter the volumename
  volumesize:
     Type: String
     Description: Enter the volumesize
  snapshotid:
     Type: String
     Description: Enter the snapshot id to make it to volume
  instanceid:
     Type: String
     Description: Enter the instanceid to attach the volume
  devicetype:
     Type: String
     Description: Enter the device type of the volume
  availabilityzone:
     Type: String
     Description: Enter the availabilityzone to create the volume form snapshot

Resources:
  volumecreation:
     Type: AWS::EC2::Volume
     Properties:
        Tags:
          - Key: Name
            Value:
              Ref: volumename
        Size:
          Ref: volumesize
        AvailabilityZone:
          Ref: availabilityzone
        SnapshotId:
          Ref: snapshotid
        VolumeType: gp2
  volumeattachment:
     Type: AWS::EC2::VolumeAttachment
     Properties:
        Device: 
           Ref: devicetype
        InstanceId:
           Ref: instanceid
        VolumeId:
           Ref: volumecreation
Outputs:
  volumeid:
     Description: output of volumeid
     Value:
        Ref: volumecreation      
